<img
    src="$ blogroot $/images/self.png"
    alt="self"
    style="float: left; margin-right: 2em;"
/>

<h1>About Contact</h1>
You can send me 
<a href="http://www.faqs.org/rfcs/rfc821.html"
>electronic mail</a> at <a href="mail-to:substack@gmail.com"
>substack@gmail.com</a>.

<h1>About Me</h1>
Oh hello! People tell me my name is James Halliday and I believe them.
I have been observing this planet for

<script type="text/javascript">
    var now = new Date();
    var birth = new Date(1987,9,22);
    var years = now.getFullYear() - birth.getFullYear() \
        - (now.getMonth() < birth.getMonth()) \
        - (now.getMonth() == birth.getMonth()
            && now.getDate() < birth.getDate()
        );
    document.write(String(years));
</script>
<noscript>
    an undisclosed number
</noscript>
of your Earth years.

Sometimes I draw pictures of robots.
Other times I write
<a href="http://codegolf.com/">terse</a>
computer programs in
<a href="http://haskell.org/">esoteric languages</a>.
I am easily amused.

<h1></h1>

<div class="caption" style="float: right; width: 325px">
<img
    src="$ blogroot $/images/interplanetary-brotherhood-of-robots.png"
    alt="interplanetary brotherhood of robots"
    width="325px" height="355px"
/>
<br />
This robot is mining one of Saturn's moons for the metals needed to build more
robots in order to expand mining to more moons.
</div>

<h1>About Robots</h1>
Robots are the future.
Robots do the jobs that humans can't do and with ruthless efficiency.
Robots are pretty great!

<h1>About Technology</h1>
<p>
This hypertext was rendered by
<a href="http://github.com/substack/slackstack">slackstack</a>,
some kind of web thing I wrote based around
<a href="http://happstack.com/">happstack</a>.
</p>

<p>
I make electronic drawings with <a href="http://inkscape.org/">inkscape</a>
and a <a
href="http://www.amazon.com/Bamboo-Medium-Tablet-Graphics-Software/dp/B000V9RL6G"
>wacom bamboo medium</a> tablet.
</p>

<h1>About Discord</h1>
In the Universe of Discord, even false things are true.
Nobody is sure who to blame for that blunder.

<h1>About Sharing</h1>
Sharing is good stuff!
Click on the
<img src="http://i.creativecommons.org/l/by-sa/3.0/us/80x15.png" />
link at the bottom of the page to learn how you can share the content contained
herein.
