<div style="float: left; margin-right: 2em;">
    <img
        src="$ blogroot $/images/self.png"
        alt="self"
        style="float: left; margin-right: 2em;"
        width="300px" height="408px"
    />
    <br />
    <img
        src="$ blogroot $/images/interplanetary-brotherhood-of-robots.png"
        alt="interplanetary brotherhood of robots"
        width="325px" height="355px"
        style="margin-top: 1em"
    />
</div>

<div style="min-height: 800px">

<h1>About Contact</h1>
<p>
    You can send me 
    <a href="http://www.faqs.org/rfcs/rfc821.html"
    >electronic mail</a> by way of
    <script type="text/javascript">
        var names = "james halliday jhalliday jh jwh mail".split(/ /);
        document.write(
            names[Math.floor(Math.random() * names.length)]
            + "@substack.net"
        );
    </script>
    <noscript>
        <a href="mail-to:mail@substack.net">mail@substack.net</a>
    </noscript>
    .
</p>

<h1>About Me</h1>

<p>
    Oh hello! People tell me my name is James Halliday and I believe them.
    I have been observing this planet for
    <script type="text/javascript">
        var now = new Date();
        var birth = new Date(1987,9,22); // 9 is actually 10 >_<
        var years = now.getFullYear() - birth.getFullYear() \
            - (now.getMonth() < birth.getMonth()) \
            - (now.getMonth() == birth.getMonth()
                && now.getDate() < birth.getDate()
            );
        document.write(String(years));
    </script>
    <noscript>
        an undisclosed number
    </noscript>
    of your Earth years.
</p>
    
<p>
    I am a <a href="http://cs.uaf.edu/">computer science student</a>
    at the University of Alaska, Fairbanks.
    
    I live in a poorly-insulated but cozy two-story building covered in chalk art
    a short walk or bike ride from campus.
</p>

<p>
    Sometimes I draw pictures of robots.
    Other times I write
    <a href="http://codegolf.com/">terse</a>
    computer programs in
    <a href="http://haskell.org/">esoteric languages</a>.
    I am easily amused.
</p>

<p>
    You can follow my wacky adventures on
        <a href="http://github.com/substack">github</a>,
        <a href="http://www.plurk.com/substack">plurk</a>,
        <a href="http://www.flickr.com/photos/substack/">flickr</a>,
        and irc.freenode.net/{##turtles,#perl-cats}
            (among 20 or so other channels)
    </ul>
</p>

<p>
    I read and occasionally comment on
    <a href="http://reddit.com/">reddit</a> and
    <a href="http://news.ycombinator.com/">hacker news</a>.
</p>

<h1>About Robots</h1>

<p>
    Robots do the jobs that humans won't do and with ruthless efficiency.
    Robots are pretty great!
</p>

<h1>About Technology</h1>
<p>
    This hypertext was rendered by
    <a href="http://github.com/substack/slackstack">slackstack</a>,
    some kind of web thing I wrote based around
    <a href="http://happstack.com/">happstack</a>.
</p>

<p>
    I make electronic doodles with
    <a href="http://inkscape.org/">inkscape</a>
    and a
    <a href="http://www.amazon.com/Bamboo-Medium-Tablet-Graphics-Software/dp/B000V9RL6G"
    >wacom bamboo medium</a> tablet.
</p>

<h1>About Sharing</h1>

<p>
    Sharing is good stuff!
    Click on the
    <img src="http://i.creativecommons.org/l/by-sa/3.0/us/80x15.png" />
    link at the bottom of the page to learn how you can share the content
    contained herein.
</p>

</div>
