<form action="$ blogRoot $/admin/new-post" method="post">
    <h1>New Post</h1>
    
    <p><label for="title">title</label></p>
    <p><input name="title" class="posttext" type="text" /></p>
    
    <p><label for="description">description</label></p>
    <p><textarea name="description" class="descbox"></textarea></p>
    
    <p><label for="body">body</label></p>
    <p><textarea name="body" class="postbox"></textarea></p>
    
    <input type="submit" value="submit" />
</form>
