<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US" xml:lang="en-US">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>$ title $</title>
    <link rel="StyleSheet" href="stylesheets/slack.css" type="text/css">
</head>
<body>
    $ header() $
    
    <div id="content">
        $ content $
    </div>
    
    $ footer() $
</body>
</html>
